export const LOADING_PRODUCTS_START = "LOADING_PRODUCTS_START";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAIL = "LOAD_PRODUCTS_FAIL";
export const LOADING_CATEGORY_START = "LOADING_CATEGORY_START";
export const LOAD_CATEGORY_SUCCESS = "LOAD_CATEGORY_SUCCESS";
export const LOAD_CATEGORY_FAIL = "LOAD_CATEGORY_FAIL";
